name: flutter_codebase
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  equatable: ^2.0.3
  hydrated_bloc: ^8.0.0
  connectivity_plus: ^2.2.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  freezed_annotation: ^1.1.0
  fluttertoast: ^8.0.8
  json_serializable: ^6.1.4
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  freezed: ^1.1.1
  flutter_native_splash: ^2.0.1+1


flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Splash Screen
# After adding your settings, run the following command in the terminal
# cmd: flutter clean
# cmd: flutter pub run flutter_native_splash:create
# To specify the YAML file location just add --path with the command in the terminal:
# cmd: flutter pub run flutter_native_splash:create --path=path/to/my/file.yaml
flutter_native_splash:
  # color: "#42a5f5"
  image: assets/images/flutter.png
  # branding_mode: center
  background_image: "assets/images/spalshbackground.png"
  # android_gravity: center
  # branding_mode: center
